# Generated by Django 2.1.4 on 2019-03-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent_hire',
            name='equipment_name',
            field=models.CharField(max_length=100),
        ),
    ]
