# Generated by Django 2.1.4 on 2019-03-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20190304_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer_details',
            name='address',
            field=models.CharField(default='b302', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmer_details',
            name='age',
            field=models.IntegerField(default=20, null=True),
        ),
        migrations.AlterField(
            model_name='farmer_details',
            name='district',
            field=models.CharField(default='pune', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmer_details',
            name='farmer_reg_id',
            field=models.CharField(default='abcd', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmer_details',
            name='first_name',
            field=models.CharField(default='rahul', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='farmer_details',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmer_details',
            name='phone_no',
            field=models.CharField(default='8805979825', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmer_details',
            name='state',
            field=models.CharField(default='Maharashtra', max_length=100, null=True),
        ),
    ]
